spring:
  application:
    name: spring-ai-functions
  ai:
    ollama:
      chat:
        model: llama3.1

api.ninjas:
  api-key: ${API_NINJAS_KEY}
  weather-url: "https://api.api-ninjas.com/v1/weather"
  stock-url: "https://api.api-ninjas.com/v1/stockprice"