spring:
  application:
    name: spring-ai-functions
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
      embedding:
        options:
          model: text-embedding-3-small

api.ninjas:
  api-key: ${API_NINJAS_KEY}
  weather-url: "https://api.api-ninjas.com/v1/weather"
  stock-url: "https://api.api-ninjas.com/v1/stockprice"